project_id = "iziunaqlgkfyasxoalwl"

[functions.sync-results]
verify_jwt = false

[functions.auto-close-matchdays]
verify_jwt = false

[functions.auto-sync-results]
verify_jwt = false
schedule = "*/3 * * * *"

[functions.fetch-fixtures]
verify_jwt = false
